### ISSUE TITLE
Add option for KR-tests for lmerTest models

### ISSUE THREAD

**Issue by palday** [palday/simr#2]
Currently, the t-tests provided by `lmerTest` use the default Satterthwaite denominator degrees of freedom. It should be possible to add an option for using Kenward-Roger degrees of freedom. This is easy enough in terms of the call to `summary` but this should be implemented in `simr` by setting a package option so as to not change the API. Since the API already supports a list of arguments to pass to `simrOptions()`, this still allows for changing the option for a single call.

**Comment by pitakakariki** [comment]
I like the idea of having default tests defined as options instead of hardcoded.
